import { config } from "dotenv";
import { resolve } from "path";
config({ path: resolve(__dirname, "../../.env.local") });

import { db } from "./index";
import { competitions } from "./schema";

async function seed() {
  console.log("正在导入竞赛数据...");

  const data = [
    {
      title: "第14届未来设计师·全国高校数字艺术设计大赛（NCDA）",
      organizer: "工业和信息化部人才交流中心",
      level: "国家级",
      overview: "教育部认定、学习强国支持的全国性数字艺术设计赛事，18个类别覆盖视觉传达到AIGC。",
      contestType: "征稿",
      tags: ["平面设计", "动画", "AIGC", "交互设计", "文创"],
      submissionDeadline: "2026-06-20",
      officialUrl: "https://www.ncda.org.cn",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "启动", date: "2025-11" }, { label: "截稿", date: "2026-06-20" }, { label: "省赛", date: "2026年7-8月" }, { label: "国赛", date: "2026年8月" }],
      categories: ["视觉传达", "动画视频", "交互设计", "人居环境", "工业产品", "时尚设计", "虚拟IP", "造型艺术", "AIGC", "文创产品", "未来设计", "乡村设计", "国潮非遗", "可持续设计"],
      eligibility: "全国高校在校本科生、研究生，高职高专学生均可参赛。",
      entryFee: { amount: 0, note: "免费" },
      awards: "总奖金超135万元，设一、二、三等奖及优秀指导教师奖。",
      specFormat: "视觉传达类A4幅面300dpi JPG，视频类MP4 720p以上。",
      aiPolicy: "设有AIGC专项赛道。",
      detailBody: "## 赛事简介\n未来设计师·全国高校数字艺术设计大赛（NCDA）是教育部中国高等教育学会认定的全国普通高校大学生竞赛排行榜内赛事，由工业和信息化部人才交流中心主办。\n\n## 赛制\n校赛 → 省赛 → 国赛三级赛制。\n\n## 赛道\n非命题赛道、产教融合&创新创业赛道、公益赛道三大赛道，共18个类别。\n\n## 时间安排\n- 启动：2025年11月\n- 作品截稿：2026年6月20日\n- 省级赛：2026年7-8月\n- 全国赛：2026年8月\n- 颁奖：2026年11月（计划）",
    },
    {
      title: "第18届全国大学生广告艺术大赛（大广赛）",
      organizer: "教育部高等教育司",
      level: "国家级",
      overview: "国内规模最大的广告艺术类赛事，覆盖平面、视频、动画、互动等类别，年参与超百万人次。",
      contestType: "征稿",
      tags: ["平面设计", "广告", "视频", "动画", "文案"],
      submissionDeadline: "2026-06-15",
      officialUrl: "https://www.sun-ada.net",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "命题发布", date: "2026-01" }, { label: "截稿", date: "2026-06-15" }, { label: "评审", date: "2026年7-8月" }],
      categories: ["平面广告", "视频广告", "动画广告", "互动广告", "广播广告", "文案广告"],
      eligibility: "全国高校在校学生（含本科生、研究生、高职高专学生）。",
      entryFee: { amount: 0, note: "免费" },
      awards: "设全国奖、省级奖、优秀指导教师奖、组织奖。",
      specFormat: "平面类A4 300dpi JPG，视频类MP4 720p以上，动画类MP4 1080p。",
      aiPolicy: "未明确禁止，须保证原创性。",
      detailBody: "## 赛事简介\n全国大学生广告艺术大赛（大广赛）由教育部高等教育司指导，是国内规模最大、覆盖面最广的高校广告艺术类学科竞赛。\n\n## 命题形式\n由企业命题+自选命题组成，每年更新命题策略单。\n\n## 参赛流程\n1. 官网下载命题\n2. 创作并上传作品\n3. 校赛选拔\n4. 省赛评选\n5. 全国总评审",
    },
    {
      title: "第18届全国三维数字化创新设计大赛（3D大赛）精英联赛",
      organizer: "全国三维数字化创新设计大赛组委会、国家制造业信息化培训中心",
      level: "国家级",
      overview: "聚焦数字工业设计、数字人居设计、数字文化设计与元宇宙创建的全国性3D创新赛事。",
      contestType: "征稿",
      tags: ["CG", "产品设计", "环艺", "数字媒体"],
      submissionDeadline: "2026-03-25",
      officialUrl: "https://ds.3ddl.net",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "报名", date: "2025-09-18" }, { label: "作品提交截止", date: "2026-03-25" }, { label: "初赛", date: "2025年10月-2026年4月" }, { label: "复赛", date: "2026年5月-6月" }, { label: "总决赛", date: "2026年7月" }],
      categories: ["数字工业设计", "数字人居设计", "数字文化设计", "元宇宙创建"],
      eligibility: "全国高校在校学生，1-5人/队，1-2名指导教师。",
      entryFee: { amount: 0, note: "免费" },
      awards: "设一、二、三等奖及特等奖，优秀指导教师奖。",
      specFormat: "3D模型GLB/mview格式，渲染图300dpi JPG。",
      aiPolicy: "未明确禁止。",
      detailBody: "## 赛事简介\n全国三维数字化创新设计大赛（3D大赛）是国家制造业信息化培训中心主办的全国性赛事，入选教育部竞赛排行榜。\n\n## 主题\n第十八届主题：数智融合 创见未来\n\n## 赛项设置\n① 数字工业设计 ② 数字人居设计 ③ 数字文化设计 ④ 元宇宙创建 + 产业命题赛 + 创新创业实践赛\n\n## 参赛组别\n国际大学生组 / 研究生组 / 本科生组 / 高职高专组",
    },
    {
      title: "第10届米兰设计周-中国高校设计学科师生优秀作品展",
      organizer: "中国教育国际交流协会、中国高等教育学会",
      level: "国家级",
      overview: "依托米兰设计周平台的国际化设计展示赛事，全国33个赛区，涵盖十多个设计方向。",
      contestType: "展览",
      tags: ["平面设计", "产品设计", "文创", "交互设计", "AIGC"],
      submissionDeadline: "2026-03-31",
      officialUrl: "https://www.milan-chn.com",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "报名", date: "2025-10" }, { label: "截稿", date: "2026-03-31" }, { label: "省赛", date: "2026年4-5月" }, { label: "国赛", date: "2026年5-6月" }],
      categories: ["视觉传达", "产品设计", "工艺美术", "虚拟IP设计", "学术论文"],
      eligibility: "全国高校设计学科师生均可参赛。",
      entryFee: { amount: 0, note: "免费" },
      awards: "设一、二、三等奖及优秀奖，获奖作品有机会在米兰设计周展出。",
      specFormat: "A3幅面300dpi JPG，视频类MP4 1080p。",
      aiPolicy: "设有'AIGC+西游神话'专项赛道（静态/视频/音乐/剧本四大类）。",
      detailBody: "## 赛事简介\n米兰设计周-中国高校设计学科师生优秀作品展由中国教育国际交流协会、中国高等教育学会联合主办，是入选教育部竞赛排行榜的国际化设计展示平台。\n\n## 特色\n获奖作品将有机会在意大利米兰设计周期间展出，为中国设计教育走向国际提供窗口。\n\n## 赛道\n专项赛场 / 命题赛场 / 非命题赛场 + 学术论文类",
    },
    {
      title: "第20届中国好创意暨全国数字艺术设计大赛",
      organizer: "中国电子视像行业协会",
      level: "国家级",
      overview: "中国第一个以数字艺术为核心的综合赛事（TOP300排行榜），涵盖24个常规赛道类别。",
      contestType: "征稿",
      tags: ["数字媒体", "动画", "平面设计", "AIGC", "摄影"],
      submissionDeadline: "2026-06-30",
      officialUrl: "https://www.cdec.org.cn",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "截稿", date: "2026-06-30" }],
      categories: ["视传应用", "数智影像", "艺术疗愈", "动画短片", "数字摄影", "思辨艺术", "社会创新", "文化遗产", "时尚生活", "AIGC"],
      eligibility: "全国高校在校学生。",
      entryFee: { amount: 0, note: "免费" },
      awards: "设一、二、三等奖及优秀奖。",
      specFormat: "静态JPG 300dpi，动态MP4 720p以上。作品不得出现学校、作者及指导教师信息。需提交2-3分钟创意说明视频。",
      aiPolicy: "设有AIGC相关赛道。",
      detailBody: "## 赛事简介\n中国好创意暨全国数字艺术设计大赛是中国第一个以数字艺术为核心、面向全国高校的综合赛事，入选教育部竞赛排行榜。\n\n## 特色类别\n视传应用、数智影像、艺术疗愈、动画短片、数字摄影、思辨艺术、高阶文明、数字生态图谱、社会创新、AI情感装置、符号化IP、文化遗产等24个类别。\n\n## 投稿方式\n以二级学院为投稿单位，需管理员审核提交。",
    },
    {
      title: "第26届白金创意国际大学生平面设计大赛",
      organizer: "中国美术学院",
      level: "行业",
      overview: "由中国美术学院主办的国际性大学生平面设计赛事，涵盖海报、品牌、书籍、字体等9大类别。",
      contestType: "征稿",
      tags: ["平面设计", "插画", "字体", "品牌设计", "海报"],
      submissionDeadline: "2026-12-15",
      officialUrl: "https://www.platinumaward.org",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "征集开始", date: "2026-11-01" }, { label: "截稿", date: "2026-12-15" }],
      categories: ["插图设计", "海报设计", "品牌形象设计", "字体设计", "信息设计", "书籍设计", "包装设计", "数字媒体设计", "综合项目设计"],
      eligibility: "全球全日制院校设计专业在校本科生、研究生、专升本、大专生；应届毕业生可参赛。每件作品作者不超过3人。",
      entryFee: { amount: 0, note: "免费" },
      awards: "全场大奖1件 ¥9,000 + 金奖9件 ¥3,000/件 + 银奖9件 ¥2,000 + 铜奖18件 ¥1,000 + 评审奖 + 优秀奖。",
      specFormat: "A4幅面300dpi RGB JPG，单张≤10M且≥4M。海报可提交动态文件MP4/GIF≤50M。书籍类入围须邮寄实物。",
      aiPolicy: "未明确提及，须保证原创。",
      detailBody: "## 赛事简介\n白金创意国际大学生平面设计大赛由中国美术学院主办，创办于2000年，是中国最具影响力的大学生平面设计竞赛之一。\n\n## 竞赛单元\n自由主题竞赛单元（9大类别）+ 主题竞赛单元\n\n## 评审标准\n视觉原创性、媒体形式独特性、表现手法艺术性\n\n## 版权\n参赛作品须原创，抄袭取消资格。组委会拥有展览、出版、宣传等权利。",
    },
    {
      title: "靳埭强设计奖（KTK设计奖）· 全球华人设计比赛",
      organizer: "靳埭强设计奖组委会",
      level: "行业",
      overview: "由国际设计大师靳埭强创办的华人设计最高奖之一，设专业组和学生组，涵盖21个参赛类别。",
      contestType: "征稿",
      tags: ["平面设计", "品牌设计", "插画", "文创", "字体", "AIGC"],
      submissionDeadline: "2026-10-31",
      officialUrl: "https://www.ktkda.cn",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "启动", date: "2026-08" }, { label: "截稿", date: "2026-10-31" }, { label: "分区赛评审", date: "2026年11月上旬" }, { label: "全国赛评审", date: "2026年11月中下旬" }, { label: "颁奖礼", date: "2026年12月中下旬" }],
      categories: ["海报设计", "动态海报", "广告设计", "字体设计", "标志设计", "VI品牌设计", "包装设计", "书籍设计", "插图设计", "二维动画", "三维动画", "空间设计", "产品设计", "交互设计", "文创设计", "UI设计", "AIGC设计"],
      eligibility: "专业组：华人设计师、教师及专业人士，不限年龄；学生组：全球华人在校学生（含应届毕业生）。",
      entryFee: { amount: 50, note: "学生组 ¥50/件；专业组 ¥150/件（系列≤5幅按1件计）" },
      awards: "设计师大奖1名 ¥15,000（学生组）+ 金奖2名 ¥5,000/名 + 银奖6名 + 铜奖12名 + 评审奖3名 + 最佳包装设计奖 + AIGC设计大奖。大师奖1名 ¥30,000（专业组）。",
      specFormat: "A3幅面300dpi RGB JPG，≤5张。多媒体≤3分钟≤100MB。",
      aiPolicy: "专设AIGC设计赛道，为该赛事首创。",
      detailBody: "## 赛事简介\n靳埭强设计奖（KTK设计奖）由国际著名设计大师靳埭强先生于1999年创办，是全球华人设计界最具影响力的奖项之一。\n\n## 赛制特色\n学生组分「分区赛」→「全国赛」两轮评审。全国八大赛区：东北、华北、华东、华中、华南、西南、西北、港澳台+海外。\n\n## 2025主题\n双主题：「重构」+「潮」+ 自由主题\n\n## 参赛类别\n21个类别，涵盖几乎所有设计领域，2025年新增AIGC设计类别。",
    },
    {
      title: "第8届GGAC全球游戏美术概念大赛",
      organizer: "GGAC组委会",
      level: "行业",
      overview: "全球最大的游戏美术专业赛事，设创作奖（面向全部创作者）和学院奖（面向在校学生）。",
      contestType: "征稿",
      tags: ["CG", "插画", "概念设计", "3D美术"],
      submissionDeadline: "2026-10-15",
      officialUrl: "https://www.ggac.com",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "开启", date: "2026-05-02" }, { label: "截稿", date: "2026-10-15" }],
      categories: ["角色概念设计", "场景概念设计", "角色模型", "世界观IP设计"],
      eligibility: "创作奖：全球创作者，无年龄限制；学院奖：全日制在读/应届毕业生。",
      entryFee: { amount: 0, note: "免费" },
      awards: "特等奖版权转让，其他获奖版权归参赛者。奖金税前金额，组委会代扣个税。设创作奖金奖、银奖、铜奖及学院奖金奖。",
      specFormat: "静态JPG/PNG 300dpi；视频MP4 16:9 1280×720以上；3D模型GLB/mview格式。须合并展示GGAC LOGO。",
      aiPolicy: "创作奖所有组别禁止AIGC；学院奖2D美术/3D模型组禁止AIGC。",
      detailBody: "## 赛事简介\nGGAC（Global Game Art Concept）是全球最大的游戏美术概念大赛，汇聚全球顶尖CG艺术家。\n\n## 赛制结构\n- GGAC主赛道：「创作奖」（全体创作者）+「学院奖」（全日制在校/应届毕业生）\n- 创作奖组别：角色概念、场景概念、角色模型、世界观IP（支持团队）\n- 学院奖组别：2D美术、3D模型、动画短片（支持团队）\n\n## 评审机制\n海选投票 + 一票晋级制（往届获奖者/组委会/评委可直接让作品晋级）",
    },
    {
      title: "第10届中国设计智造大奖（DIA）",
      organizer: "中国美术学院",
      level: "国家级",
      overview: "中国首个国际级工业设计奖项，聚焦智能制造与生活美学，金奖奖金高达百万元。",
      contestType: "征稿",
      tags: ["产品设计", "工业设计", "交互设计"],
      submissionDeadline: "2026-07-30",
      officialUrl: "https://www.di-award.org",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "征集", date: "2026-01" }, { label: "截稿", date: "2026-07-30" }, { label: "评审", date: "2026年8-10月" }, { label: "颁奖", date: "2026年12月" }],
      categories: ["文化创新", "生活智慧", "产业装备", "前沿科技"],
      eligibility: "全球企业、设计机构、设计师及高校师生均可参赛。",
      entryFee: { amount: 0, note: "免费" },
      awards: "金奖100万元/件，银奖、铜奖及佳作奖若干。",
      specFormat: "产品实物照片+设计说明，详情见官网。",
      aiPolicy: "未明确。",
      detailBody: "## 赛事简介\n中国设计智造大奖（DIA）是中国美术学院主办的国际性工业设计奖项，为中国首个国际化综合性设计大奖。\n\n## 奖项设置\n- 金奖：奖金100万元/件\n- 银奖：奖金20万元/件\n- 铜奖：奖金10万元/件\n\n## 评审标准\n创新性、功能性、美学性、社会价值、经济价值。",
    },
    {
      title: "第19届中国大学生计算机设计大赛",
      organizer: "教育部高等学校计算机类专业教学指导委员会",
      level: "国家级",
      overview: "涵盖数字媒体设计、交互设计、信息可视化、AIGC等方向的全国性高校计算机设计赛事。",
      contestType: "征稿",
      tags: ["数字媒体", "交互设计", "AIGC", "UI", "动画"],
      submissionDeadline: "2026-04-30",
      officialUrl: "https://www.jsjds.org",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "校赛", date: "2026-03" }, { label: "省赛截稿", date: "2026-04-30" }, { label: "国赛", date: "2026年7-8月" }],
      categories: ["软件应用与开发", "微课与教学辅助", "物联网应用", "大数据应用", "人工智能应用", "信息可视化设计", "数媒静态设计", "数媒动漫与短片", "数媒游戏与交互设计"],
      eligibility: "全国高校在校学生。",
      entryFee: { amount: 0, note: "免费" },
      awards: "设一、二、三等奖及优秀奖。",
      specFormat: "静态作品300dpi JPG/PNG，视频MP4 1080p。",
      aiPolicy: "设有AI应用赛道。",
      detailBody: "## 赛事简介\n中国大学生计算机设计大赛由教育部计算机类专业教学指导委员会主办，入选教育部竞赛排行榜。\n\n## 赛制\n校赛 → 省赛 → 国赛三级赛制。\n\n## 特色\n涵盖数字媒体设计、交互设计、信息可视化等方向，是计算机与艺术交叉领域的重要赛事。",
    },
    {
      title: "第15届全国美展·艺术设计展区",
      organizer: "文化和旅游部、中国美术家协会",
      level: "国家级",
      overview: "五年一届的最高规格国家级美术大展，艺术设计展区涵盖建筑、景观、室内、公共艺术、平面设计等方向。",
      contestType: "展览",
      tags: ["平面设计", "产品设计", "环艺", "服装设计", "文创"],
      submissionDeadline: "2026-09-01",
      officialUrl: "https://www.caanet.org.cn",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "征稿", date: "2026-03" }, { label: "截稿", date: "2026-09-01" }, { label: "评审", date: "2026年9-11月" }, { label: "展览", date: "2026年12月" }],
      categories: ["平面设计", "环境设计", "工业设计", "服装设计", "工艺美术", "数字艺术"],
      eligibility: "全国美术工作者、设计师及高校师生。",
      entryFee: { amount: 0, note: "免费" },
      awards: "设金奖、银奖、铜奖及入选作品。",
      specFormat: "A3幅面300dpi JPG，实物须按要求邮寄。",
      aiPolicy: "未明确。",
      detailBody: "## 展览简介\n全国美术作品展览（全国美展）是由文化和旅游部、中国美术家协会联合主办的五年一届国家级综合性美术大展，为中国美术界最高规格展览。\n\n## 艺术设计展区\n涵盖平面设计、环境设计、工业设计、服装设计、工艺美术、数字艺术等方向。\n\n## 重要性\n入选全国美展是设计作品获得国家认可的里程碑式荣誉。",
    },
    {
      title: "GDC设计奖",
      organizer: "深圳市平面设计协会（SGDA）",
      level: "行业",
      overview: "中国最具影响力和权威性的平面设计专业奖项之一，成立于1992年，每两年一届。",
      contestType: "征稿",
      tags: ["平面设计", "品牌设计", "字体", "交互设计", "文创"],
      submissionDeadline: "2026-10-31",
      officialUrl: "https://www.sgda.cc",
      status: "published" as const,
      source: "manual" as const,
      deadlines: [{ label: "征集开始", date: "2026-08" }, { label: "截稿", date: "2026-10-31" }, { label: "评审", date: "2026年11月" }, { label: "颁奖", date: "2026年12月" }],
      categories: ["品牌形象", "包装设计", "出版物", "海报", "文字设计", "插画", "环境图形", "交互设计", "综合设计"],
      eligibility: "全球华人设计师、设计机构及在校学生。",
      entryFee: { amount: 0, note: "学生组免费，专业组收费详见官网" },
      awards: "全场大奖 + 金奖/银奖/铜奖 + 评审奖 + 优异奖。",
      specFormat: "A3幅面300dpi JPG，多媒体MP4 1080p。",
      aiPolicy: "未明确。",
      detailBody: "## 奖项简介\nGDC设计奖（Graphic Design in China）由深圳市平面设计协会（SGDA）创立于1992年，是中国最具影响力的平面设计专业奖项之一。\n\n## 特色\n每两年一届，被誉为中国平面设计界的'奥斯卡'。\n\n## 参赛类别\n品牌形象、包装设计、出版物、海报、文字设计、插画、环境图形、交互设计、综合设计。",
    },
  ];

  for (const item of data) {
    await db.insert(competitions).values(item);
    console.log(`✓ ${item.title}`);
  }

  console.log(`\n导入完成！共 ${data.length} 条竞赛信息。`);
  process.exit(0);
}

seed();
